### ISSUE TITLE
can i change uuid of vdo device ?

### ISSUE THREAD

**Issue by zhujing3** [dm-vdo/vdo#15]
in some case , we need a fullcopy of vdo device (using dd if=/dev/vdo1 of=/dev/sdc)

origin: sdb
mirror: sdc

then export these two disk to a linux box( iscsi ), copy &edit /etc/vdoconf.yml, change name/device value

final : vdo start -a , origin(sdb) is actived,but mirror disk report error!

vdo: ERROR - Could not set up device mapper for vdo2
vdo: ERROR - device-mapper : create ioctl on vdo-xxxxxxxxxxx(same as vdo1) failed : Device or resource busy

any tips? thank you

**Comment by zhujing3** [comment]
im tring edit disk's  uuid using hexedit ,but vdodumpconfig failed:

vdo : ERRROR - vdodumpconfig: allocateVDO failed for '/dev/sdc' with Unknow error 2066

**Comment by sweettea** [comment]
There isn't currently a way, and it's checksummed so just hexediting won't work.

**Comment by rhawalsh** [comment]
I have opened https://bugzilla.redhat.com/show_bug.cgi?id=1713749 to track this request.

**Comment by zhujing3** [comment]
> I have opened https://bugzilla.redhat.com/show_bug.cgi?id=1713749 to track this request.

Any progress, please?

**Comment by bjohnsto** [comment]
Hi. 

We're currently working on a complete solution for this but it's not likely to be done any time soon. If you need a more immediate solution, I can work on getting you a tool that should fix your issue. However, it is not going to be fully tested or have documentation or anything. It would very much be buyer beware. If you are interested in this, please let me know here.

**Comment by zhujing3** [comment]
> Hi.
> 
> We're currently working on a complete solution for this but it's not likely to be done any time soon. If you need a more immediate solution, I can work on getting you a tool that should fix your issue. However, it is not going to be fully tested or have documentation or anything. It would very much be buyer beware. If you are interested in this, please let me know here.

ok, sound good. a tool is enough for us to  resolve this problem. thx for your  appreciated working!

**Comment by bjohnsto** [comment]
I've uploaded the tool in a fork of the tree. You can get it here ....
https://github.com/bjohnsto/vdo/tree/uuid_util
The commit number is 
https://github.com/bjohnsto/vdo/commit/9f004367374094835abd3952d0cd4c7a2adfe3a2

Once you clone that, you need to do a make and then you should find a tool in utils/vdo/user called vdorewriteuuid. Steps to follow after that are: 

1. Make sure your vdo volume is stopped. I'm guessing it already should be because of the uuid conflict failure but you should make sure.
2. Run the vdodumpconfig tool on the device where vdo is stored. It will show the current uuid of that device. 
3. Run the vdorewriteuuid tool on the same device 
4. Rerun vdodumpconfig to confirm the uuid change. 
5. At that point, you should be able to call vdo start for the device and it should start. 

Hopefully this allows you to move forward in working with VDO.

**Comment by zhujing3** [comment]
> I've uploaded the tool in a fork of the tree. You can get it here ....
> https://github.com/bjohnsto/vdo/tree/uuid_util
> The commit number is
> [bjohnsto@9f00436](https://github.com/bjohnsto/vdo/commit/9f004367374094835abd3952d0cd4c7a2adfe3a2)
> 
> Once you clone that, you need to do a make and then you should find a tool in utils/vdo/user called vdorewriteuuid. Steps to follow after that are:
> 
> 1. Make sure your vdo volume is stopped. I'm guessing it already should be because of the uuid conflict failure but you should make sure.
> 2. Run the vdodumpconfig tool on the device where vdo is stored. It will show the current uuid of that device.
> 3. Run the vdorewriteuuid tool on the same device
> 4. Rerun vdodumpconfig to confirm the uuid change.
> 5. At that point, you should be able to call vdo start for the device and it should start.
> 
> Hopefully this allows you to move forward in working with VDO.

it works， thx a lot
![YS4 91TQBUKJ9F4S9%NJX94](https://user-images.githubusercontent.com/11979531/61099027-98126180-a493-11e9-93d1-71e244939d9e.png)
