### ISSUE TITLE
Questions about vdo version

### ISSUE THREAD

**Issue by kjy8901** [dm-vdo/vdo#19]
Hey, I've found thatthere's no option on vdo (not means vdoformat or vdostats). Is that what you've designed for?
Otherwise, if it is okay to add a version option as new one on vdo,
My opinion is putting **statistics/VDOReleaseVersions.py** into **vdo-manager/utils** or **vdo-manager**, rather than the latest solution which is putting into **vdo-manager/statistics**.
Plus, it looks better to state the version on **vdomgmnt/VDOService.py** just like **VDOStatistics.py** has its staticsVersion.
I wants some your opinion. Thx

**Comment by kjy8901** [comment]
I would like to add version option to vdo (ex. vdo version      output=6.2.1.102    or  131337.28)
but vdostats or vdoformat have version option.
Is it your intent not to have a version option in vdo?
if not your intent, will i be able to add the vdo version option?
and I think you should put statistics/VDOReleaseVersions.py under vdo-manager/utils or vdo-manager.
what do you think?

i'm sorry. i'm not used to English
thank you. corwin

**Comment by corwin** [comment]
We will be adding a version option to the vdo utility, but that will likely not be done for several months.

In the meantime, if you would like to add it yourself, the numbers in VDOReleaseVersions.py are not what you should use. The release versions are used to disambiguate statistics versions across branches of the VDO code so that vdostats can determine whether it is the correct version for the statistics it gets from the kvdo module. That number is only updated when we branch the codebase, not every time there is a change to the vdo utility or other tools.

The version you want would be the same one as is reported by vdoformat. You can find that value as the VDO_VERSION variable in vdo/utils/vdo/user/Makefile. Probably the simplest way to implement the version option for the vdo utility would be to just have it call vdoformat --version and scrape the output.

Hope this helps...

**Comment by kjy8901** [comment]
I'm appreciated your answer. Thank you corwin

**Comment by kjy8901** [comment]
Hello, corwin!
I haven't told you before, but I want to contribute to VDO.
So I asked you about version options before.
I have developed the current version option.

result:

[root@kjy ~]# vdo version
vdo major version is: 6.2.1.102
[root@kjy ~]# vdo version --release
vdo release version is: 133524.30

but I am worried about that..
1. I added VDOMajorVersion. Is this the same way you think of development?
2. I modified this part because versionOperation in VDOOperation does not seem to be used.
If you could tell us more specifically how to develop the version, it would be helpful to each other.

and
`https://github.com/kjy8901/vdo/commit/e315cd993abe18497f980a5eb06b3fce4f46c855`
The above link is the branch to which the version option was applied.
If you are okay, check it out and let me know what you need to fix.

Thank you for always.

**Comment by corwin** [comment]
Hi!

I very much appreciate both your interest and willingness to contribute to our project!

However, your interpretation of the meaning of the release version numbers is incorrect. Let me try another explanation.

There have been many releases of the VDO software over the last nine years (most of them from before it was acquired by Red Hat and open-sourced). In general, it is not possible to use VDO volumes created from one VDO release branch using the module from a different branch. As it happens, the three branches currently on GitHub happen to be upgrade compatible without any explicit offline upgrade required. However, this will likely not remain the case forever, and certainly was not true in the past.

All of VDO's on-disk data structures have their own version numbers, and the statistics are versioned as well. Every time we release an incompatible fork of the VDO code, that fork is given a code name corresponding to an element, and for that element, we assign a release version number (which number is derived from our internal version control system and is simply an integer). The release versions are used to differentiate the version number spaces across incompatible releases. For example, in the VDO super block is a "master version number" which is incremented every time the on disk format of any component of the VDO changes. The 6.1 and 6.1.1 branches of VDO, both part of the "magnesium" fork, have master version 67. As it happens, the on disk format for 6.2, "aluminum," is identical to the magnesium format, and so it also has master version 67. However, if we were to make a format change to magnesium, and a different format change to aluminum, both of those changes would be master version 68, but they would no longer be compatible. This is where the release version comes in by allowing the code to differentiate between magnesium 68 and aluminum 68. If we didn't use the release versions, we would need to make sure that all of the on-disk component version numbers were unique across all release branches, which is much more work and also more error prone. 

In addition to the on-disk versioning, every version of VDO which we publish has an actual version number of the form w.x.y.z. It is this version number, and not the release version number, which is meaningful in terms of the vdo script. Unlike the on-disk component version numbers, this number is guaranteed to be unique across all VDO releases and is the same number which "vdoformat  --version" prints. The vdoformat code gets this value from the CURRENT_VERSION variable defined in the Makefile which builds it. The actual generation of that Makefile is part of the automated process we use to generate the releases we push to GitHub. Due to the nature of that automation, and the structure of the Makefiles in the vdo project, it is not a trivial task to plumb that version number directly into the python code. However, it is a trivial matter to have the vdo script implement the correct --version option by merely having it invoke 'vdoformat --version' and displaying the resulting output. For the latest VDO release on GitHub, for example, this would print "6.2.1.102".

Some additional confusion may result from the fact that vdostats --version prints out an entirely different version number in the form x.y where x is a release version number, and y is a statistics version. This same pair of values is included in the raw statistics from the VDO device and is used to ensure that the version of vdostats being run can understand the statistics being output from a running VDO volume.

I hope this rather long-winded explanation helps to clarify the situation.

Thanks!

**Comment by kjy8901** [comment]
I really appreciate that.
I will develop it by referring to your words.
Have a nice day.

**Comment by kjy8901** [comment]
Hello corwin
Can you tell me the location of the automated script you are talking about?
And if you want to run `VDO version`, is it output `6.2.1.102`?
or is it output `133524.30`?
and i didn't understand you want
1: call `vdoformat --version ` and print
or
2: Call the version of MakeFile

I'm sorry to bother you.
If you do not understand the above, I will explain it again.

Thank you corwin.

**Comment by rhawalsh** [comment]
Hi @kjy8901 , 

I believe running `vdo version` should simply just return the output of `vdoformat --version` (which would be 6.2.1.102).

**Comment by kjy8901** [comment]
hi @rhawalsh 
thanks your opinion.
I will develop it.

**Comment by kjy8901** [comment]
Hello, corwin.

long time no see.
I modified 'vdo version'.
PR number is '23'
Link is 'https://github.com/dm-vdo/vdo/pull/23'

I modified VersionOperation because I think it doesn't used.
If you are using it, we will modify it.
I would be grateful if you could let me know what to fix.
Thanks.

**Comment by corwin** [comment]
Hi, sorry for the delay in getting back to you. Your change looks pretty good to me but I'm going to have the rest of the team look it over in the next few days.

Meanwhile, another question for you, what name and email address (if any) would you like us to use for you in the contributors file?

**Comment by kjy8901** [comment]
Hi, corwin

I want use 
Jin-young Kwon <gc757489@gmail.com>

Please tell me if there is any part of the source code to fix.

thanks, corwin.
have a good day.

**Comment by corwin** [comment]
Hi Jin-young,

Your changes are in the release I just pushed. Version 6.2.2.33.

Thanks for your help!

corwin

**Comment by kjy8901** [comment]
Hi corwin,

Thank you!
