### ISSUE TITLE
Btrfs on top of vdo volume

### ISSUE THREAD

**Issue by brunorf** [dm-vdo/vdo#20]
First of all, sorry if that is the wrong place for this kind of question.

I'm testing vdo (master branch) on an ubuntu 18.04 server and it's shining.
The only thing that I'm missing is snapshot capabilities. So, I'm wondering if there are any concerns  using btrfs on top of vdo.
So, my setup would be mdadm managing a software RAID-5, vdo on top of that array managing dedups and btrfs on top of that, managing lightweight snapshots.

I take a survey on docs, but can't find any kind of recommendations/directions

Thanks in advance!

**Comment by rhawalsh** [comment]
Hi, thanks for posting.  I'm happy to hear you're having a good experience with VDO!

We don't currently actively test btrfs on top of VDO, but I don't believe we have any known restrictions that would prevent you from using it.  Is there any reason you would rather use btrfs instead of something like LVM snapshots?

Currently, we document what is not supported in a VDO configuration in the [Storage Admin Guide](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/storage_administration_guide/index#vdo-qs-requirements) as well as LVM stacking configurations in the [Stacking LVM Volumes Knoweldgebase article](https://access.redhat.com/articles/2106521#vdo).  If you have any questions about this, please feel free to ask.

For future reference, there's a mailing list for working with VDO development, [vdo-devel](https://www.redhat.com/mailman/listinfo/vdo-devel); please feel free to send an email to the list with questions like these, since this isn't specifically a bug or problem that you're encountering.  I will attempt to answer your questions here, however.

If you do end up encountering any issues, they should certainly be reported so that they can be investigated.  Note that any time you report issues, it is important that you specify which version of the VDO software you're running (which right now, can be based on github commit ID or Tag), the kernel version you're running (and if it's been modified in any way) and any other relevant details about the layers above and below the VDO volume (such as LVM or MDRAID, etc.).  Additionally, if you have a specific kind of workload being applied to the VDO device, that could be helpful in validating your configuration as well.

**Comment by brunorf** [comment]
Thank you for helping me.
Actually, I misread the docs and think that I couldn't use LVM on top of vdo, sorry for that.
For now, I'm just testing it and if I can't find any big issues, I plan to setup a small backup server with vdo on it.
For now, I'm backing up a photographer work, with many duplicated files. Also, I would like to keep track of a feel days of modifications (delete, rename, and so on); that is why I'm looking for snapshots.


Thanks again for your help
See you!
