### ISSUE TITLE
Change index on existing volume?

### ISSUE THREAD

**Issue by dragon2611** [dm-vdo/vdo#27]
Is there anyway to change/rebuild the index on an existing volume?

I stupidly set it to 0.25GB and the default of Dense,

I presume changing index sparse in vdoconf.yml would explode things but what about increasing index memory and leaving the other settings alone?

**Comment by rhawalsh** [comment]
Hi @dragon2611 ,

There is not a way to resize the index on an already-created VDO volume.  This would require a significant reshape operation to occur on the volume and potentially shrinking the VDO data area, which is also not something that is available.  This is because the index region on the backing storage is placed before the VDO volume (i.e. blocks 1 through <size_of_index>).

Changing the index sparse setting in vdoconf.yml does not change the functionality of the index.  It only affects the reporting of whether the index is sparse in the `vdo status --verbose` output.

There is actually a bug in this behavior that I will be opening a bug for (I'll link here when it is created).  If the VDO volume and index are online/available, the output of `vdo status --verbose` should report the index configuration of the actual index.  Instead, it reports what is in the config file.  The data stored in the config file is used to be able to reference the configuration for volumes that are offline/unavailable (for convenience/reporting reasons).

You will need to create a new VDO volume with a larger index.  Are you sure that you want to go with a sparse index?  Or was that just an attempt to still use the same "0.25" configuration?  Note that a "sparse 0.25G" index will take ~10x the on-disk storage of a "dense 0.25G" index.

Please let me know if you have further questions.

Thanks.

**Comment by dragon2611** [comment]
I went with 2GB/Sparse on the other volume, (Probably a mistake, but I have enough ram) , the 2 Volumes are around ~10TB each.

Once I've moved data I can re-create this one.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/vdo-ig-administering-vdo#vdo-ig-config-uds-index is the reason for picking sparse.

**Comment by rhawalsh** [comment]
Hi @dragon2611 ,

Thanks for the response.  Understood.  Please note that using a 2G sparse vs a 2G dense index won't have an effect on RAM, but the storage usage will increase.  Before you create a new volume, I would suggest reviewing these sections in the documentation [0]:
  - 29.2.1. UDS Index Memory Requirements -  "For a sparse index, UDS will provide a deduplication window of 10 TB per 1 GB of RAM. A 1 GB sparse index is generally sufficient for up to 40 TB of physical storage."
  - Table 29.2
  - Table 29.3

[0] https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/storage_administration_guide/vdo-qs-requirements#vdo-ig-example-requirements

Thanks,
Andy

**Comment by rhawalsh** [comment]
> There is actually a bug in this behavior that I will be opening a bug for (I'll link here when it is created).
This bug has been created and can be found [here](https://bugzilla.redhat.com/show_bug.cgi?id=1790983)

**Comment by rhawalsh** [comment]
Closing this bug.  We will track the bug from the above comment in the BZ itself.
