### ISSUE TITLE
can i add an argument when vdo create?

### ISSUE THREAD

**Issue by lingxu-wxw** [dm-vdo/vdo#29]
I want to add an argument(like "LZ4") in "vdo create" to choose compression algorithm,
so I try to edit the code in vdo front end (python part), 
but there is a bug in "dmsetup create vdo0 --uuid=xxx --table 'xxx' " as shown after.
I find code of "dmsetup create" is in vdo-manager/vdomgmnt/VDOService.py,
how can i fix it? It is just a test and I want to know if i can add an argument when vdo create.

KEY POINT:
    dmsetup create vdo0 --uuid VDO-53da712d-b543-4e30-b005-39f011ae8811 --table '0 209715200 vdo V2 /dev/disk/by-id/nvme-INTEL_SSDPEDMD800G4_CVFT6496004L800CGN-part1 52428800 4096 32768 16380 on async LZ4 vdo0 maxDiscard 1 ack 2 bio 2 bioRotationInterval 64 cpu 2 hash 2 logical 2 packer 2 physical 2'
vdo: ERROR - Could not set up device mapper for vdo0
......
vdo: ERROR - device-mapper: reload ioctl on vdo0  failed: Invalid argument

TOTAL MESSAGE:
Creating VDO vdo0
    grep MemAvailable /proc/meminfo
    modprobe kvdo
    vdoformat --uds-checkpoint-frequency=0 --uds-memory-size=0.25 --logical-size=100G --force /dev/disk/by-id/nvme-INTEL_SSDPEDMD800G4_CVFT6496004L800CGN-part1
    vdodumpconfig /dev/disk/by-id/nvme-INTEL_SSDPEDMD800G4_CVFT6496004L800CGN-part1
Starting VDO vdo0
    dmsetup status --target vdo vdo0
    grep MemAvailable /proc/meminfo
    modprobe kvdo
    vdodumpconfig /dev/disk/by-id/nvme-INTEL_SSDPEDMD800G4_CVFT6496004L800CGN-part1
    vdodumpconfig /dev/disk/by-id/nvme-INTEL_SSDPEDMD800G4_CVFT6496004L800CGN-part1
    dmsetup create vdo0 --uuid VDO-53da712d-b543-4e30-b005-39f011ae8811 --table '0 209715200 vdo V2 /dev/disk/by-id/nvme-INTEL_SSDPEDMD800G4_CVFT6496004L800CGN-part1 52428800 4096 32768 16380 on async LZ4 vdo0 maxDiscard 1 ack 2 bio 2 bioRotationInterval 64 cpu 2 hash 2 logical 2 packer 2 physical 2'
vdo: ERROR - Could not set up device mapper for vdo0
Removing VDO vdo0
Stopping VDO vdo0
    dmsetup status --target vdo vdo0
    dd if=/dev/zero of=/dev/disk/by-id/nvme-INTEL_SSDPEDMD800G4_CVFT6496004L800CGN-part1 oflag=direct bs=4096 count=1
vdo: ERROR - device-mapper: reload ioctl on vdo0  failed: Invalid argument

**Comment by rhawalsh** [comment]
Hi @lingxu-wxw.

Can you clarify why you are attempting this?  That will help us with providing better feedback.

As it is, simply modifying VDO Manager (the python suite), will not be sufficient for changing the compression algorithm being used by VDO; there are also some kernel-side modifications that would need to be done as well in the kvdo project.

In addition to that, with the way that VDO compression is implemented, even if you do end up achieving better compression rates on the 4K blocks, you will never be able to compress more than 14 fragments into a single 4K block.

**Comment by lingxu-wxw** [comment]
Hi, I am a student and I try to optimize vdo as my graduation project (with my teacher's help).

We know that we should edit vdo project and kvdo project both, and I do so. We use a new Intel hardware accelerator called QAT to replace LZ4 as a new compression algorithm, and we also design a Zlib version for performance evaluation. We add two new function called kvdoCompressWorkWithQAT(...) and kvdoCompressWorkWithZlib(...) (just like LZ4 kvdoCompressWork(...)) in kvdo-project/vdo/kernel/dataKVIO.c  to implement QAT and Zlib compression algorithm, and try to add an if branch in kvdoCompressDataVIO(...) to get compatibility. We decide to add an argument called --compressPolicy to specified algorithm, we try to edit vdo-project to let vdo can distinguish the new argument "compressPolicy", and now have some problem, so I write this issue for help.

In vdo-project, I imitate “writePolicy” to add "compressPolicy", add many similar function, because I think this is similar. I find problem is perhaps in vdo-project/vdo-manager/vdomgmnt/VDOService.py.
In def start(...), dmsetup create throw a exception, and def _generateDeviceMapperTable(self), I add "self.compressPolicy" behind "self.writePolicy". If I remove "self.compressPolicy" in _generateDeviceMapperTable() vdoConf, vdo create can run OK. So I think problem is here.

QAT algorithm‘s compression ratio is better (I use fio to test it, about 50%, use vdostat), and throughput/CPU utilization is little worse than LZ4; as a negative case, Zlib‘s compression ratio is good, but throughput is too low.

**Comment by sweettea** [comment]
Hi lingxu;

Right now you're making compress policy to be a parameter you can set each time you start the VDO. If you want to do that, I think the problem is that kernel/deviceConfig.c isn't expecting the new parameter. https://github.com/lingxu-wxw/vdo-qat-async/blob/master/vdo/kernel/deviceConfig.c#L53 needs to change to expect the new parameter -- those two arrays answer "how many parameters does the 'dmsetup create vdo0 --uuid ... --table '...' 'command take in the table part?". Specifically, I think your change will work if you bump the last two numbers up by 1, to 10 and 9, because the python code generates a 'version 2' table, and the last number in each array is at index 2.

If this were intended for the long-term, I would encourage you to make a 'version 3' of the table instead of modifying version 2. You would need to update TABLE_VERSION to 3, append 10 and 9 to REQUIRED_ARGC and POOL_NAME_ARG_INDEX, and put your compressPolicy code in an 'if (config->version == 3) {...}' statement.

I might also suggest (if you're not just trying to do a performance experiment) to store what policy is used in the header of the compressed blocks -- you would want to edit compressedBlock.[ch] to add that information to the header, and find some way to return that information back in getCompressedBlockFragment(), and then decompress with the appropriate algorithm in uncompressReadBlock(). But that's not strictly necessary for your performance work if you make sure to never try to read a compressed block with the wrong algorithm :).

Let me know if there's more I can do to help!

**Comment by lingxu-wxw** [comment]
Thanks a lot! I changed REQUIRED_ARGC and POOL_NAME_ARG_INDEX, and solved another related problem, and now it works. Thank you~

**Comment by sweettea** [comment]
Awesome! Let us know if there's anything else we can help with.

**Comment by jasontally** [comment]
Was this ever upstreamed?

**Comment by corwin** [comment]
Nothing was ever submitted to us, so this was not upstreamed.

Furthermore, we don't think this is a good idea for two reasons.

First, VDO's metadata maps blocks at a granularity of 4K, and needs to be able to treat each 4K logical block independently. Therefore, the way that VDO implements compression is by taking the compressed versions of multiple 4K blocks, and packing them together into single 4K blocks. Because of the structure of VDO's block map, at most 14 logical blocks can be aggregated into a single 4K block on disk.

All of the compression algorithms we've looked at which do better than LZ4 either get those benefits when applied to larger inputs than the 4K VDO is limited to, or don't do enough better than LZ4 that VDO actually saves more space. For example, if LZ4 is able to compress some set of 4K blocks to, say, down to 256 bytes each, 14 of those could be written to a single block (and leaving 512 bytes of that block empty). If some other compressor got them down to 200 bytes each, they would still get written to a single 4K block on disk. There would be an additional 784 bytes unused in that block, but because of the metadata limitation, nothing can take advantage of those extra bytes.

The only case where there might be benefits is if some other compression algorithm does better enough on 4K inputs that LZ4 is not able to fit 14 compressed blocks in 4K, but the other algorithm is able to fit more. We've seen very few cases where this is true, and the benefits are far outweighed by the complexity of modifying the on disk format of compressed blocks to encode which compression algorithm was used and of adding the ability to configure that algorithm.

Second, the format and interface changes required to encode the compression algorithm cause issues for compatibility with existing VDO volumes which again, don't seem worth addressing given the limited or non-existent benefit.
