### ISSUE TITLE
vdo and kmod-kvdo missing from Fedora repos

### ISSUE THREAD

**Issue by lessfoobar** [dm-vdo/vdo#62]
Why vdo and kmod-kvdo are not to be found in the standard Fedora repos. Why are they not supported for Fedora as they are for RHEL and Centos Stream. Has RH moved from VDO? Is there an announcement that I've missed?

**Comment by slegendr** [comment]
Hello @lessfoobar. Thank you for reaching out. No, RH hasn't moved from VDO. The reason that vdo and kmod-kvdo are not in the standard Fedora repos are due to Fedora having a strict no-kmod policy. Since vdo and kmod-kvdo have not been incorporated into the upstream Linux kernel, we are only able to deliver them for Fedora via COPR. The rhawalsh/dm-vdo COPR repo is kept up to date with our latest push for the EL releases (https://copr.fedorainfracloud.org/coprs/rhawalsh/dm-vdo/). 

We are working very had to get VDO accepted into the upstream Linux kernel so that it will be generally available on all distros. However, we do not have a firm date on when that will be finished.
