### ISSUE TITLE
Correct mount for VDO devices in /etc/fstab after reboot

### ISSUE THREAD

**Issue by serjponomarev** [dm-vdo/vdo#7]
VDO service started after mount fstab and fstab not find VDO device.

Please add to vdo.service:
**Before=local-fs.target**

This solves the problem

**Comment by drckeefe** [comment]
Thanks, Sergey.  I'm looking at this change.

Dennis Keefe


On Tue, Feb 13, 2018 at 11:17 AM, Sergey Ponomarev <notifications@github.com

**Comment by drckeefe** [comment]
Sergey,

vdo.service starts and stops VDO volumes and by doing so loads the kvdo and
usd kernel modules.
Mounting a filesystem on VDO should be done using an option in the fstab or
mount unit for systemd.

Here is an example of using "x-systemd.requires=vdo.service" in the
/etc/fstab file for VDO volumes.

/dev/mapper/vdo1        /VDO                    xfs
 defaults,discard,x-systemd.requires=vdo.service      0 0

Systemd unit file to mount a VDO volume

cat /etc/systemd/system/multi-user.target.wants/VDO.mount

[Unit]
Description = Mount filesystem that lives on VDO
name = VDO.mount
Requires = kvdo.service systemd-remount-fs.service
After = multi-user.target
Conflicts = umount.target

[Mount]
What = /dev/mapper/vdo1
Where = /VDO
Type = xfs
Options = discard

[Install]
WantedBy = multi-user.target


- Dennis

Dennis Keefe
Manager, Software Engineering
Red Hat
dkeefe@redhat.com

On Tue, Feb 13, 2018 at 11:17 AM, Sergey Ponomarev <notifications@github.com

**Comment by slesru** [comment]
Really , it should be possible to use fstab,  from redhat manual:

" To configure the file system to mount automatically, use either the /etc/fstab file or a systemd mount unit:

    If you decide to use the /etc/fstab configuration file, add one of the following lines to the file:
        For the XFS file system:

        /dev/mapper/vdo_name /mnt/vdo_name xfs defaults,x-systemd.requires=vdo.service 0 0 "

**Comment by c0d3z3r0** [comment]
I am using udev for starting vdo devices because I have a more or less complicated setup (disks->ZFS->ZVOL->LUKS->VDO->LVM->...).
This also solves any systemd related service order problems.
Maybe this is helpful for anyone so I post it here.

~~~
systemctl disable vdo.service

cat <<"EOF" >/usr/local/bin/vdo_startdev
#!/usr/bin/env python3

import os
import sys
from vdo import vdomgmnt

device = os.path.realpath(sys.argv[1])
cfile = vdomgmnt.Defaults.confFile
config = vdomgmnt.Configuration(cfile, mustExist=True)

devmap = {os.path.realpath(v.device): v for k,v in config.getAllVdos().items()}
vdo = devmap.get(device)
if not vdo:
  sys.exit(0)

vdo.start()
if vdo.activated and not vdo.running:
  print("Error: VDO {} could not be started".format(vdo.getName()), file=sys.stderr)
  sys.exit(1)
sys.exit(0)
EOF

chmod +x /usr/local/bin/vdo_startdev

cat <<"EOF" >/etc/udev/rules.d/90-kvdo.rules
SUBSYSTEM=="block", ACTION=="add|change", ENV{PATH}="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", RUN+="/usr/local/bin/vdo_startdev /dev/%k"
EOF

udevadm control --reload
~~~

**Comment by drckeefe** [comment]
Zagarjr,
Which options are you using in /etc/fstab?  
Have you tried "_netdev,x-systemd.device-timeout=0,x-systemd.requires=vdo.service" in fstab?
Also, which options from Red Hat doesn't work, so it can be fixed. 
Thanks.
